Discard invalid paths
CrowdStrike/CAST pull request #22
Opened 2022-01-19 05:48 UTC by jashley1992

If the installation registry keys have invalid paths, I've experienced some issues with the execution of cast.exe.

This addition to the PowerShell script tests to see if the discovered path exists, prior to running CAST.
If the path does not exist, it discards the path.

2022-01-19 20:11 UTC, bk-cs requested changes
Could you make it simpler by testing the paths while using `Sort-Object`?

```
$Directories = $Directories | Sort-Object -Unique | Where-Object { Test-Path $_ -EA 0 }
```

2022-01-19 21:08 UTC, jashley1992 commented
Wow that was a much simpler way to do that. Excellent suggestion!

I changed the pull request and requested re-review, hopefully I did that right.

2022-01-19 22:51 UTC, bk-cs commented
Thanks, I think this is a helpful suggestion. If you get a chance to figure out how to de-duplicate the paths, let me know... ;)

2022-01-19 22:51 UTC, merged

2022-01-20 05:59 UTC, jashley1992 commented
@bk-cs What about something like this? There are probably better ways to do this, but it seems to work fairly well for me. Definitely not finalized, just some POC code to test the idea..

```
 $DirDelim = [System.IO.Path]::DirectorySeparatorChar
 $RegexDD = [regex]::Escape($DirDelim)
 
 $FinalList = New-Object 'System.Collections.Generic.List[string]'
 $RemovedPaths = New-Object 'System.Collections.Generic.List[string]'

 [array] $Directories = ('Software\Microsoft\Windows\CurrentVersion\Uninstall\*',
 'Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*').foreach{
     (Get-ItemProperty -Path "Registry::\HKEY_LOCAL_MACHINE\$_" | Where-Object InstallLocation).InstallLocation
     foreach ($UserSid in (Get-WmiObject Win32_UserProfile | Where-Object { $_.SID -like 'S-1-5-21-*' }).SID) {
         (Get-ItemProperty -Path "Registry::\HKEY_USERS\$UserSid\$_" | Where-Object InstallLocation).InstallLocation
     }
 }
 $Directories += (Get-Process | Where-Object { $_.Path }).Path | Split-Path
 $Directories = $Directories | Sort-Object -Unique | Where-Object { Test-Path $_ -EA SilentlyContinue }


 $Directories | % {
     
     $CurrentDir = $_.TrimEnd($RegexDD)
 
     if ($RemovedPaths -notcontains $CurrentDir) {
 
         foreach ($Path in $Directories) {
             If ($Path.StartsWith("$($CurrentDir)\","CurrentCultureIgnoreCase") -and $Path.TrimEnd($RegexDD) -ne $CurrentDir) {
                 Write-Warning "DUPLICATE PATH FOUND: $Path"
                 $RemovedPaths.Add($Path.TrimEnd($RegexDD))
             }
         }
 
         if ($FinalList -notcontains $CurrentDir -and $RemovedPaths -notcontains $CurrentDir) {
             
             Write-Warning "Final List Add: $CurrentDir"
             $FinalList.Add($CurrentDir)
         }
     }
 
 }

$FinalListCount = ($FinalList).Count
$OriginalCount = ($Directories).Count

Write-Host "Reduced in-scope paths by $($OriginalCount - $FinalListCount)" -ForegroundColor Green
Write-Host "Paths Removed:" -ForegroundColor Red
$RemovedPaths

Write-Host "Final Listing:" -ForegroundColor Green
$FinalList | Sort-Object
```